### PR TITLE
Fix OpenGL ES types change in Android

### PR DESCRIPTION
**Pull request by WesleyKhoiVo**
Fix for issue: #111

### CODE REVIEW

**Comment by Hossein-Noroozpour** [comment]
Hi @WesleyKhoiVo ,

Great thanks for the time and all the efforts you put on this PR!

As you can see, it has been a long time that the project didn’t have much progress, this is mostly because of several new thoughts and design changes that are happening in it and as a matter of fact, there wasn’t enough time for hammering those ideas and changes.

One of the major changes that is going to happen in the project is, achieving a new design in overall of the engine to seamlessly support RTX and conventional raster based rendering with lowest overhead and maybe it’s going to be lightning without rain with consideration of my time.

And as a friendly suggestion, I personally recommend putting your time on cool projects like [Amethyst](https://github.com/amethyst/amethyst).

Thanks again!

Best regards,
Hossein Noroozpour

**Comment by WesleyKhoiVo** [comment]
Hi @Hossein-Noroozpour,
Thanks for your answer and suggestion, but before that may be you merge this PR and make this repo is archive? I thought this repo still active

**Comment by Hossein-Noroozpour** [comment]
Hi @WesleyKhoiVo ,

This repo is active and soon it's going to have huge changes (especially the code you worked on, it is not going to be the same anymore). Currently, I'm doing the hammering thing that I've mentioned in a different repo when they got to the mature state, I'm gonna bring them in here.

**Comment by Hossein-Noroozpour** [comment]
However, I'm going to merge your commit

**Comment by WesleyKhoiVo** [comment]
Nice, I will close the issue too

**Pull request merged**
